control_dt: 0.02

num_actions: 23


msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"


leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
kps: [100, 100, 100, 150, 40, 40, # leg
    100, 100, 100, 150, 40, 40, # leg
    ]
kds: [2, 2, 2, 4, 2, 2, # leg
      2, 2, 2, 4, 2, 2, # leg
  ]

default_angles: [  -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                ]

# arm & waist
arm_waist_joint2motor_idx: [12, 13, 14, 
                            15, 16, 17, 18, 
                            22, 23, 24, 25]

arm_waist_kps: [150, 150, 150, # waist
                40, 40, 40, 40, # arm
                40, 40, 40, 40] # arm

arm_waist_kds: [4, 4, 4, 
                5, 5, 5, 5,
                5, 5, 5, 5]

arm_waist_target: [ 0, 0, 0,
                    0, 0.4, 0, 1.2,
                    0, -0.4, 0, 1.2]

# wrist
wrist_joint2motor_idx: [19, 20, 21,
                        26, 27, 28]

wrist_kps: [20, 20, 20,
            20, 20, 20]
            
wrist_kds: [1, 1, 1,
            1, 1, 1]

wrist_target: [0, 0, 0,
               0, 0, 0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.5 # full is 0.5

